export const FETCHED_ECONOMICAL_ARTICLE = 'FETCHED_ECONOMICAL_ARTICLE'
export const ECONOMICAL_ARTICLE_LOADING = 'ECONOMICAL_ARTICLE_LOADING'
export const ECONOMICAL_ARTICLE_FAILED = 'ECONOMICAL_ARTICLE_FAILED'

export const FETCHED_TECHNICAL_ARTICLE = 'FETCHED_TECHNICAL_ARTICLE'
export const TECHNICAL_ARTICLE_LOADING = 'TECHNICAL_ARTICLE_LOADING'
export const TECHNICAL_ARTICLE_FAILED = 'TECHNICAL_ARTICLE_FAILED'

export const FETCHED_SPORT_ARTICLE = 'FETCHED_SPORT_ARTICLE'
export const SPORT_ARTICLE_LOADING = 'SPORT_ARTICLE_LOADING'
export const SPORT_ARTICLE_FAILED = 'SPORT_ARTICLE_FAILED'

export const FETCHED_SCIENCE_ARTICLE = 'FETCHED_SCIENCE_ARTICLE'
export const SCIENCE_ARTICLE_LOADING = 'SCIENCE_ARTICLE_LOADING'
export const SCIENCE_ARTICLE_FAILED = 'SCIENCE_ARTICLE_FAILED'